from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


Json = dict[str, Any]


@dataclass(frozen=True)
class ToolCall:
    id: str
    name: str
    arguments: Json


@dataclass(frozen=True)
class AssistantTurn:
    content: str = ""
    tool_calls: tuple[ToolCall, ...] = ()
    # Why the model stopped, as the provider reported it. "length" means the reply was
    # cut off at the output-token limit, so any tool call it carries may have TRUNCATED
    # ARGUMENTS -- see agent.turn_fault. None when the provider said nothing.
    finish_reason: str | None = None
    # The model's own thinking, when the provider returns it. Shown to an
    # operator; never fed back as content.
    reasoning: str = ""
    # ⚠️ THE PROVIDER'S OWN ENCODED REASONING BLOCKS, WHICH MUST BE ECHOED
    # VERBATIM on the next request of a tool-calling exchange. OpenRouter is
    # explicit: "the entire sequence of consecutive reasoning blocks must match
    # the outputs generated by the model during the original request". Drop them
    # and a reasoning model's next turn is rejected. The flattened, readable
    # `reasoning` above is NOT a substitute and is never sent back.
    reasoning_details: tuple[Json, ...] = ()
    # Token counts and cost for this turn, as the provider reported them.
    usage: "Json | None" = None


@dataclass(frozen=True)
class ToolResult:
    ok: bool
    data: Any = None
    error: str | None = None

    def as_json(self) -> Json:
        result: Json = {"ok": self.ok}
        if self.data is not None:
            result["data"] = self.data
        if self.error is not None:
            result["error"] = self.error
        return result


@dataclass(frozen=True)
class AgentOutcome:
    status: str
    summary: str
    model_calls: int
    events: tuple[Json, ...] = field(default_factory=tuple)
    # Summed across the run, when the provider reported any. `None` means
    # nobody said -- which is not the same as zero, and must not render as it.
    usage: "Json | None" = None
